"""empty message

Revision ID: 22ae8f0ab82c
Revises: e1667d06c4ed
Create Date: 2023-10-12 14:20:55.551384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ae8f0ab82c'
down_revision = 'e1667d06c4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clerkID', sa.String(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('clerkID')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
